name: oraaq
description: "Oraaq App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_extensions: ^2.0.14
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.3
  cron: ^0.6.1
  cupertino_icons: ^1.0.8
  curl_logger_dio_interceptor: ^1.0.0
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.3
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^7.0.0
  flutter_screenutil: ^5.9.1
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  google_sign_in: ^6.2.1
  gradient_borders: ^1.0.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  line_icons: ^2.0.3
  liquid_swipe: ^3.1.0
  loading_animation_widget: ^1.2.1
  logger: ^2.3.0
  material_symbols_icons: ^4.2741.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

# dart run flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path: "assets/app_icon/appicon_ios.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon/appicon_android.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  ios: true
  android: true
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/app_icon/appicon_android.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/
    - assets/app_icon/
